import { Oswald } from "next/font/google";
import "./globals.scss";
import Header from "@/components/layout/header/Header";
import { AppProvider } from "@/components/AppContext";

// import Header from "../components/layout/header/Header";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Vertpak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <AppProvider>
          <Header />

          {children}
        </AppProvider>
      </body>
    </html>
  );
}
